package com.printmanager;

import javafx.embed.swing.SwingFXUtils;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.image.ImageView;
import javafx.scene.image.WritableImage;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Screen;
import javafx.stage.Stage;
import javafx.geometry.Rectangle2D;
import javafx.collections.FXCollections;

import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.List;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.layout.Pane;
import javafx.scene.layout.Priority;
import javafx.scene.layout.Region;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.scene.text.Font;
import javafx.scene.text.FontWeight;
import javafx.scene.text.FontPosture;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PDFViewer {
    private static final Logger logger = LoggerFactory.getLogger(PDFViewer.class);
    private final PDFService pdfService = new PDFService();
    private File currentFile;
    private VBox contentBox;
    private TextField endField;
    private ScrollPane scrollPane;

    public interface FileItemCallback {
        void add(File file, String customName, String style, String overlay, int start, int end, boolean subtract);
    }

    public void show(File file, boolean isInitialAdd, FileItemCallback onResult) {
        this.currentFile = file;
        Stage stage = new Stage();
        stage.setTitle("PDF Viewer & Manual Split: " + file.getName());

        contentBox = new VBox(10);
        contentBox.setPadding(new Insets(10));
        
        Pane drawPane = new Pane(contentBox);
        drawPane.setStyle("-fx-background-color: white;");
        
        scrollPane = new ScrollPane(drawPane);
        scrollPane.setFitToWidth(true);

        TextField startField = new TextField("1"); startField.setPrefWidth(40);
        endField = new TextField("1"); endField.setPrefWidth(40);
        HBox rangeBox = new HBox(5, new Label("Pages:"), startField, new Label("-"), endField);
        rangeBox.setAlignment(Pos.CENTER_LEFT);

        ComboBox<String> styleCombo = new ComboBox<>(FXCollections.observableArrayList("Simplex", "Duplex", "Booklet"));
        styleCombo.setValue("Simplex"); styleCombo.setPrefWidth(90);
        styleCombo.setOnAction(e -> refreshPreview(currentFile, contentBox, endField, scrollPane, styleCombo.getValue()));

        CheckBox subtractCheck = new CheckBox("Split & Remove");
        subtractCheck.setSelected(true);
        subtractCheck.setTooltip(new Tooltip("Remove these pages from the original file after adding to queue."));

        Button addBtn = new Button(isInitialAdd ? "Add to Queue" : "Add Split Part");
        addBtn.setStyle("-fx-base: #4CAF50; -fx-text-fill: white; -fx-font-weight: bold;");
        addBtn.setOnAction(e -> {
            try {
                int start = Integer.parseInt(startField.getText());
                int end = Integer.parseInt(endField.getText());
                
                if (start < 1 || end < start) {
                    throw new Exception("Invalid range: " + start + "-" + end);
                }

                File splitFile = pdfService.splitPages(currentFile, start, end);
                boolean subtract = !isInitialAdd && subtractCheck.isSelected();
                
                // The filename will now be generated by App.java for consistency
                onResult.add(splitFile, null, styleCombo.getValue(), "", start, end, subtract);
                
                if (isInitialAdd) {
                    stage.close();
                } else {
                    if (subtract) {
                        File remaining = pdfService.removePages(currentFile, start, end);
                        if (remaining == null) {
                            stage.close();
                        } else {
                            this.currentFile = remaining;
                            refreshPreview(currentFile, contentBox, endField, scrollPane, styleCombo.getValue());
                        }
                    } else {
                        int totalPages = pdfService.getPageCount(currentFile);
                        if (end < totalPages) {
                            startField.setText(String.valueOf(end + 1));
                            endField.setText(String.valueOf(totalPages));
                        }
                    }
                }
            } catch (Exception ex) { 
                Alert alert = new Alert(Alert.AlertType.ERROR, "Invalid split configuration: " + ex.getMessage());
                alert.show();
            }
        });

        Button closeBtn = new Button("Close");
        closeBtn.setOnAction(e -> stage.close());

        HBox toolBar = new HBox(10, new Region(), closeBtn);
        if (onResult != null) {
            toolBar.getChildren().add(1, rangeBox);
            toolBar.getChildren().add(2, new Label("Style:"));
            toolBar.getChildren().add(3, styleCombo);
            if (!isInitialAdd) toolBar.getChildren().add(4, subtractCheck);
            toolBar.getChildren().add(isInitialAdd ? 4 : 5, addBtn);
        }
        
        HBox.setHgrow(toolBar.getChildren().get(0), Priority.ALWAYS);
        toolBar.setPadding(new Insets(10));
        toolBar.setAlignment(Pos.CENTER_LEFT);
        toolBar.setStyle("-fx-background-color: #f8f8f8; -fx-border-color: #ccc; -fx-border-width: 0 0 1 0;");

        VBox layout = new VBox(toolBar, scrollPane);
        VBox.setVgrow(scrollPane, Priority.ALWAYS);

        refreshPreview(file, contentBox, endField, scrollPane, styleCombo.getValue());

        Rectangle2D bounds = Screen.getPrimary().getVisualBounds();
        Scene scene = new Scene(layout, bounds.getWidth() * 0.85, bounds.getHeight() * 0.85);
        stage.setScene(scene);
        stage.show();
    }

    private void refreshPreview(File file, VBox contentBox, TextField endField, ScrollPane scrollPane, String style) {
        contentBox.getChildren().clear();
        new Thread(() -> {
            try {
                File displayFile = file;
                if ("Booklet".equalsIgnoreCase(style)) {
                    displayFile = pdfService.createBookletPDF(file, "Left", "A4");
                }
                
                final File finalFile = displayFile;
                int pages = pdfService.getPageCount(finalFile);
                javafx.application.Platform.runLater(() -> endField.setText(String.valueOf(pages)));
                
                for (int i = 0; i < pages; i++) {
                    BufferedImage bimg = pdfService.renderPage(finalFile, i, 1.2f);
                    WritableImage fxImage = SwingFXUtils.toFXImage(bimg, null);
                    javafx.application.Platform.runLater(() -> {
                        ImageView iv = new ImageView(fxImage);
                        iv.setPreserveRatio(true);
                        iv.fitWidthProperty().bind(scrollPane.widthProperty().subtract(40));
                        contentBox.getChildren().add(iv);
                    });
                }
                
                // Cleanup temp booklet file after rendering (it's copied into memory via fxImage)
                if (finalFile != file) {
                    // Slight delay to ensure render is done
                    Thread.sleep(1000);
                    finalFile.delete();
                }
            } catch (Exception e) { logger.error("Preview error", e); }
        }).start();
    }
}